### PR TITLE
Extend with zoom

### PR DESCRIPTION
**Pull request by staradayev**
This is fix of the lost parentheses, while I've prepared pull request. This lost parentheses are cause zoom functionality not work at all.  Also Tests has been updated. 

Can be tested at _DragSelect/__tests__/functional/zoom.html_

Please sorry about this, this is my fail.

### CODE REVIEW

**Comment by staradayev** [comment]
@ThibaultJanBeyer do you have a chance to look into?

**Comment by ThibaultJanBeyer** [comment]
good that this did not affect any other user

**Comment by ThibaultJanBeyer** [comment]
Just a small note, please chose more descriptive pull request title names next time :)

**Comment by staradayev** [comment]
Thank you!

**Pull request merged**
