### PR TITLE
Get cursor position difference single element fix

### PR DESCRIPTION
**Pull request by RealTJ**
Should theoretically fix the issue #13 testing needed

### CODE REVIEW

**Comment by ThibaultJanBeyer** [comment]
on first sight, this looks very good.
Maybe you can do some testing on your side, I’ll do some testings on my side. Unfortunately, today is a busy day so it might take a bit.

Don’t forget to pull the latest version into your branch before tho’ as it seems you’re working on  v1.7.20 but the newest is 1.7.21

**Comment by RealTJ** [comment]
Thats ok, i was busy all the time. I will update it to the newest version.

**Comment by ThibaultJanBeyer** [comment]
Hey RealTJ, did you do some testing?
so I found time to do some tests myself…
Remeber the use-cases:

Dragging:
```
1 Click: 0, 0
Drag: the difference between 1st click and current mouse position.
```

Singleclicks:
```
1st click: 0, 0
2nd click: the difference between 2nd click and 1st click
3rd click: the difference between 3rd click and 2nd click
```

So your solution is working fine on single clicks (it always calculates against the last position) but unfortunately, do not work for dragging (there it should always start with 0,0).

One solution I have in mind to handle both cases is letting the user choose within `getCursorPositionDifference` between what and what he wants to get the difference.
Let’s discuss that in the ticket #13.

I’ll add some comments to the code on what to do so that I can merge the changes for now.

Thanks for your contribution

**Comment by ThibaultJanBeyer** [comment]
So this cursor position difference is a bit messed up as it seems because of 2 usecases in one. If you fix one, the other one won’t work and vice versa. Can you think of a solution for both to work?

**Comment by RealTJ** [comment]
> Hey RealTJ, did you do some testing?
> so I found time to do some tests myself…
> Remeber the use-cases:

After posting i got really busy, since i had some other issues to solve. But i'm taking the time now.

> So your solution is working fine on single clicks (it always calculates against the last position) but unfortunately, do not work for dragging (there it should always start with 0,0).

> One solution I have in mind to handle both cases is letting the user choose within getCursorPositionDifference between what and what he wants to get the difference.

Hey thanks for saying that, i had that feeling like something is not right, but i could not point at it. Maybe it is not a good idea to try to solve it in one Function? You have a different functions for selecting (callback) and one for each single Element (onElementSelect). 

Wouldn't it be better if we had a different functions, the first behaves for the callback and the second one for onElementSelect. It is kinda convoluted, i'm not too happy with the solution, but nothing else comes to mind.

**Comment by ThibaultJanBeyer** [comment]
Hmm what comes to my mind is that the user can choose himself between what cursor difference he wants:
- by default it would be what we have now: initial cursor position vs current cursor position
- but the user could change it to reflect the difference between: current position vs last position of previous selection. To make this more obvious I would probably rename `lastCursorPos` to `previousCursorPos` otherwise it’s to hard to differentiate.

To differenciate the two, this could just be a boolean within the `getCursorPositionDifference` method. What do you think?

**Comment by RealTJ** [comment]
> To differenciate the two, this could just be a boolean within the getCursorPositionDifference method. What do you think?

Sounds good, i will implement it that way. Having choice is good and there are no nasty surprises. Should i update the comment for the function?

**Comment by ThibaultJanBeyer** [comment]
> Should i update the comment for the function?

yes please update the comment and also the documentation, that would be flawless 👍

**Comment by RealTJ** [comment]
Ok i updated the function and the documentation. My test so far looked good.

**Comment by ThibaultJanBeyer** [comment]
Hey, so I tested it, it seems ok for now. I’ll merge it.
There are still small things regarding these calculations I want to fix before releasing the next version tho’.
Thank you RealTJ

**Comment by RealTJ** [comment]
> There are still small things regarding these calculations I want to fix before releasing the next version tho’.

Sure, let me know when you are done, then i can take a look at it.

**Comment by ThibaultJanBeyer** [comment]
@RealTJ it took me ages to find the issue. Actually, it was something you suggested long before, we had to set the new position at initialization to be correct. It was just 1 or two lines of code.
The biggest change for the user is that it now returns negative values instead of positive if the mouse is more to the left. This is to be consequent with the X/Y Axis. See the [changelog](https://github.com/ThibaultJanBeyer/DragSelect/blob/master/changelog.md#1721-23).'
Should be all fine now.
Thanks again for the great help, I would otherwise probably not even have noticed it 👍

**Comment by RealTJ** [comment]
@ThibaultJanBeyer I'm happy to help! 
Sorry for the late reply, was ill the whole week.

**Comment by ThibaultJanBeyer** [comment]
Oh snap, Get well soon!

**Pull request merged**
