### PR TITLE
fix toggleSelection

### PR DESCRIPTION
**Pull request by VampireAchao**
I used npm to install DragSelect,but I found this function is not work as unexpected.
Until I debug and found this,then I fixed it,maybe this is my first pull request about fontend opensource project!!!
By the way,I wanted to use `Array.prototype.group()`,but it is a experimental API.

### CODE REVIEW

**Comment by VampireAchao** [comment]
expectation expectation 🙇‍♂️

**Comment by VampireAchao** [comment]
I am so confused 😕

**Comment by ThibaultJanBeyer** [comment]
What is this doing? Just looking at the code it would not change anything? What is it supposed to change? Can you explain please? Also looks like a test is failing after your change, can you fix?

**Comment by VampireAchao** [comment]
At line 340 in the DragSelect.js `this.removeSelection(elements`
This elements is from outside
It is not every single `el`

About test failed,I'm trying to find out why..

**Pull request closed without merging**
